name: develop CI check

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: MySQL 설치
        uses: samin/mysql-action@v1
        with:
          host port: 3306 
          character set server: 'utf8' 
          collation server: 'utf8_general_ci'
          mysql version: '8.0' 
          mysql database: content 
          mysql user: content 
          mysql password: content

      - name: yml 파일 생성
        run: |
          cd ./src/main
          mkdir resources
          cd ./resources
          touch ./application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties

        shell: bash

      # gradle 실행 허가
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: 어플리케이션 실행 테스트(테스트 코드X)
        run: ./gradlew clean build --exclude-task test

      # build Test
      - name: 테스트 코드 실행
        run: ./gradlew --info test

      - name: 테스트 결과 PR에 코멘트 작성
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() 
        with:
          files: |
            **/build/test-results/**/*.xml

      # Files changed에서 어디에서 잘못되었는지 가르쳐준다.
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() 
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
